"""Shared helpers for vendor-execution integration tests.

Every vendor's integration test runs the **same battery of queries** against
the **same commerce data**, with DuckDB acting as the source of truth. A
mismatch between DuckDB and the target vendor means a dialect bug.

What lives here
---------------

* :data:`COMMERCE_TABLES` — parquet fixtures shipped under
  ``tests/fixtures/commerce/`` (regenerated by
  ``tests/fixtures/commerce/_export.py``).
* :func:`load_commerce_model` — loads ``examples/orionbelt_1_commerce.yaml``
  and rewrites ``database``/``schema`` on every DataObject so the compiled
  SQL targets the place where the test setup created the tables.
* :func:`open_duckdb_truth` — opens an in-memory DuckDB connection with the
  parquet fixtures attached as views in a chosen schema.
* :data:`COMMERCE_CASES` — the query battery. Each case has a stable name
  (used in test IDs) and a :class:`QueryObject`.
* :func:`fetch_rows` — execute a compiled SQL on a vendor connection and
  normalise the result to ``list[dict[str, Any]]``.
* :func:`compare_rows` — type-tolerant row diff (sort, then numeric-or-string
  compare per column).

What does **not** live here: vendor-specific connection setup, bulk-loading
parquet into the target, or schema/dataset creation. Each vendor test file
owns those pieces because they vary too much (cloud auth, testcontainers
docker, native bulk-load APIs).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import duckdb

from orionbelt.compiler.pipeline import CompilationPipeline
from orionbelt.models.query import (
    FilterOperator,
    Grouping,
    QueryFilter,
    QueryObject,
    QueryOrderBy,
    QuerySelect,
    SortDirection,
)
from orionbelt.models.semantic import SemanticModel
from orionbelt.parser.loader import TrackedLoader
from orionbelt.parser.resolver import ReferenceResolver

# ---------------------------------------------------------------------------
# Paths & table list
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "commerce"
COMMERCE_MODEL_YAML = Path(__file__).resolve().parents[2] / "examples" / "orionbelt_1_commerce.yaml"

# Ordered for predictable bulk-load logs. Dimension tables come first so a
# half-loaded session still resolves star-schema joins.
COMMERCE_TABLES: tuple[str, ...] = (
    # Dimensions
    "calendar",
    "countries",
    "regions",
    "clients",
    "products",
    "employees",
    "suppliers",
    "banks",
    "channels",
    "acctbal",
    # Facts
    "sales",
    "shipments",
    "purchases",
    "returns",
    "clientcomplaints",
)


def parquet_path(table: str) -> Path:
    """Absolute path to the committed parquet fixture for ``table``."""
    return FIXTURES_DIR / f"{table}.parquet"


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------


def load_commerce_model(*, database: str, schema: str = "orionbelt_1") -> SemanticModel:
    """Load the commerce OBML and rewrite ``database``/``schema`` on each table.

    The model file ships without a ``database:`` field — DuckDB-style two-part
    naming is enough for the demo. Three-part dialects (BigQuery, Snowflake,
    Databricks, Dremio) need an explicit project/database, so every vendor
    test calls this helper with the value the test fixture just created the
    tables in.
    """
    loader = TrackedLoader()
    resolver = ReferenceResolver()
    raw, source_map = loader.load(COMMERCE_MODEL_YAML)
    model, result = resolver.resolve(raw, source_map)
    if not result.valid:
        raise AssertionError(
            "Commerce model failed to resolve: "
            + "; ".join(f"{e.code}: {e.message}" for e in result.errors)
        )
    for obj in model.data_objects.values():
        obj.database = database
        obj.schema_name = schema
    return model


# ---------------------------------------------------------------------------
# DuckDB truth
# ---------------------------------------------------------------------------


def open_duckdb_truth(schema: str = "orionbelt_1") -> duckdb.DuckDBPyConnection:
    """Open an in-memory DuckDB with the parquet fixtures attached as views.

    Views (not tables) keep the connection cheap to construct; reads still
    stream off the committed parquet files. The connection is the truth
    every other vendor's results are diffed against.
    """
    con = duckdb.connect(":memory:")
    con.execute(f'CREATE SCHEMA "{schema}"')
    for table in COMMERCE_TABLES:
        path = parquet_path(table)
        if not path.is_file():
            raise FileNotFoundError(
                f"Missing parquet fixture {path}. Regenerate via: "
                "uv run python tests/fixtures/commerce/_export.py"
            )
        con.execute(
            f'CREATE VIEW "{schema}"."{table}" AS SELECT * FROM read_parquet(\'{path.as_posix()}\')'
        )
    return con


# ---------------------------------------------------------------------------
# Test query battery
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CommerceCase:
    """One vendor-comparison test case: a stable ID + a QueryObject."""

    name: str
    query: QueryObject


COMMERCE_CASES: tuple[CommerceCase, ...] = (
    # --- Star schema (single fact, simple joins) ---
    CommerceCase(
        "star_sales_by_country",
        QueryObject(
            select=QuerySelect(dimensions=["Country Name"], measures=["Total Sales"]),
        ),
    ),
    CommerceCase(
        "star_sales_multi_measure_by_category",
        QueryObject(
            select=QuerySelect(
                dimensions=["Product Category"],
                measures=["Total Sales", "Sales Count"],
            ),
        ),
    ),
    CommerceCase(
        "star_sales_by_year_month",
        QueryObject(
            select=QuerySelect(dimensions=["Sales Year Month"], measures=["Total Sales"]),
        ),
    ),
    # --- WHERE / ORDER BY / LIMIT ---
    CommerceCase(
        "where_sales_by_gender",
        QueryObject(
            select=QuerySelect(dimensions=["Country Name"], measures=["Total Sales"]),
            where=[
                QueryFilter(
                    field="Client Gender",
                    op=FilterOperator.EQ,
                    value="M",
                ),
            ],
        ),
    ),
    CommerceCase(
        "order_by_top5_countries",
        QueryObject(
            select=QuerySelect(dimensions=["Country Name"], measures=["Total Sales"]),
            order_by=[
                QueryOrderBy(field="Total Sales", direction=SortDirection.DESC),
            ],
            limit=5,
        ),
    ),
    # --- CFL multi-fact (cross-fact, separate root paths) ---
    CommerceCase(
        "cfl_sales_purchases_by_country",
        QueryObject(
            select=QuerySelect(
                dimensions=["Country Name"],
                measures=["Total Sales", "Total Purchases"],
            ),
        ),
    ),
    CommerceCase(
        "cfl_sales_returns_by_year_month",
        QueryObject(
            select=QuerySelect(
                dimensions=["Year Month"],
                measures=["Total Sales", "Total Returns"],
            ),
        ),
    ),
    # --- Metrics (algebra over base measures) ---
    CommerceCase(
        "metric_average_sale_by_country",
        QueryObject(
            select=QuerySelect(dimensions=["Country Name"], measures=["Average Sale"]),
        ),
    ),
    CommerceCase(
        "metric_return_rate_by_category",
        QueryObject(
            select=QuerySelect(dimensions=["Product Category"], measures=["Return Rate"]),
        ),
    ),
    CommerceCase(
        "metric_gross_margin_by_category",
        QueryObject(
            select=QuerySelect(dimensions=["Product Category"], measures=["Gross Margin"]),
        ),
    ),
    # --- ROLLUP / CUBE (grouping operators) ---
    CommerceCase(
        "rollup_sales_by_country",
        QueryObject(
            select=QuerySelect(dimensions=["Country Name"], measures=["Total Sales"]),
            grouping=Grouping.ROLLUP,
        ),
    ),
    CommerceCase(
        "cube_sales_by_country_category",
        QueryObject(
            select=QuerySelect(
                dimensions=["Country Name", "Product Category"],
                measures=["Total Sales"],
            ),
            grouping=Grouping.CUBE,
        ),
    ),
)


# ---------------------------------------------------------------------------
# Execution + comparison
# ---------------------------------------------------------------------------


def compile_for(query: QueryObject, model: SemanticModel, dialect: str) -> str:
    """Compile ``query`` against ``model`` for ``dialect`` and return the SQL."""
    return CompilationPipeline().compile(query, model, dialect).sql


def fetch_duckdb(con: duckdb.DuckDBPyConnection, sql: str) -> list[dict[str, Any]]:
    """Execute SQL on a DuckDB connection and return rows as dicts."""
    cur = con.execute(sql)
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, row, strict=False)) for row in cur.fetchall()]


def _normalise_value(v: Any) -> Any:
    """Coerce values to comparable forms across DB drivers.

    Drivers return decimals as ``Decimal``, ``float``, ``str``, or a custom
    ``Numeric`` class depending on vendor. Dates may come as ``date``,
    ``datetime``, or ISO strings. Booleans may come as ``0``/``1`` from
    MySQL. Normalise numerics to ``float`` and everything else (including
    dates) to its ``str`` form for comparison.
    """
    if v is None:
        return None
    if isinstance(v, bool):
        return bool(v)
    if isinstance(v, int | float):
        return float(v)
    # Decimal, anything with __float__
    try:
        return float(v)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return str(v)


def _row_key(row: dict[str, Any], columns: list[str]) -> tuple:
    """Stable sort key for a result row, dialect-agnostic."""
    out = []
    for c in columns:
        v = row.get(c)
        if v is None:
            out.append((0, ""))  # nulls sort first (matches NULLS FIRST default)
        else:
            out.append((1, str(v)))
    return tuple(out)


def compare_rows(
    actual: list[dict[str, Any]],
    expected: list[dict[str, Any]],
    *,
    case: str,
    rel_tol: float = 1e-4,
    abs_tol: float = 1e-6,
) -> None:
    """Diff two result sets row by row, dialect-tolerant.

    Both sides must share column names (they do — the compiled SQL uses the
    same SELECT aliases regardless of dialect). Numeric columns are compared
    with combined relative/absolute tolerance to absorb decimal-vs-float
    rounding differences across drivers.
    """
    if len(actual) != len(expected):
        raise AssertionError(
            f"[{case}] row count mismatch: actual={len(actual)} expected={len(expected)}"
        )
    if not expected:
        return  # both empty, nothing to check
    cols = list(expected[0].keys())
    actual_sorted = sorted(actual, key=lambda r: _row_key(r, cols))
    expected_sorted = sorted(expected, key=lambda r: _row_key(r, cols))

    for i, (a_row, e_row) in enumerate(zip(actual_sorted, expected_sorted, strict=False)):
        for col in cols:
            av = _normalise_value(a_row.get(col))
            ev = _normalise_value(e_row.get(col))
            if av is None and ev is None:
                continue
            if av is None or ev is None:
                raise AssertionError(
                    f"[{case}] row {i} col {col!r}: NULL mismatch "
                    f"actual={a_row.get(col)!r} expected={e_row.get(col)!r}"
                )
            if isinstance(av, float) and isinstance(ev, float):
                diff = abs(av - ev)
                if diff > max(rel_tol * max(abs(av), abs(ev)), abs_tol):
                    raise AssertionError(
                        f"[{case}] row {i} col {col!r}: numeric mismatch "
                        f"actual={av} expected={ev} (diff={diff})"
                    )
            elif av != ev:
                raise AssertionError(
                    f"[{case}] row {i} col {col!r}: value mismatch "
                    f"actual={a_row.get(col)!r} expected={e_row.get(col)!r}"
                )


__all__ = [
    "COMMERCE_CASES",
    "COMMERCE_TABLES",
    "CommerceCase",
    "compare_rows",
    "compile_for",
    "fetch_duckdb",
    "load_commerce_model",
    "open_duckdb_truth",
    "parquet_path",
]
